[tool.bumpversion]
current_version = "4.1.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
allow_dirty = false
commit = true
tag = true
tag_name = "v{new_version}"
message = "Bump version: {current_version} â†’ {new_version}"

[[tool.bumpversion.files]]
filename = "gradle.properties"

[[tool.bumpversion.files]]
filename = "src/main/resources/application.properties"

[[tool.bumpversion.files]]
filename = "README.md"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
